export const data = [
  { "player": "AshenCyrus", "game": "Dark Souls III"},
  { "player": "BlueTrainBlitz", "game": "Pokemon Red and Blue"},
  { "player": "CraftAdvBlitz", "game": "Minecraft"},
  { "player": "CraftEggsBlitz", "game": "Minecraft"},
  { "player": "FactoryBlitz", "game": "Factorio"},
  { "player": "HollowBlitz", "game": "Hollow Knight"},
  { "player": "L2PBlitz", "game": "A Link to the Past"},
  { "player": "LADXBlitz", "game": "Links Awakening DX"},
  { "player": "LOZBlitz", "game": "The Legend of Zelda"},
  { "player": "RedDexBlitz", "game": "Pokemon Red and Blue"},
  { "player": "SMario64Blitz", "game": "Super Mario 64"},
  { "player": "SMWBlitz", "game": "Super Mario World"},
  { "player": "WitnessBlitz", "game": "The Witness"},
  { "player": "ChefMTS", "game": "Overcooked! 2"},
  { "player": "ChupaKH2", "game": "Kingdom Hearts 2"},
  { "player": "ChupaOOT", "game": "Ocarina of Time"},
  { "player": "ChupaPKMN", "game": "Pokemon Red and Blue"},
  { "player": "GundamXLADX", "game": "Links Awakening DX"},
  { "player": "GundamXLTTP", "game": "A Link to the Past"},
  { "player": "GundamXSPIN", "game": "Timespinner"},
  { "player": "GundamXSUPMET", "game": "Super Metroid"},
  { "player": "HollowCyrus", "game": "Hollow Knight"},
  { "player": "Jockquest", "game": "DLCQuest"},
  { "player": "Jockstar", "game": "Stardew Valley"},
  { "player": "Jocksub", "game": "Subnautica"},
  { "player": "MegarushLTTP", "game": "A Link to the Past"},
  { "player": "MegarushWitness", "game": "The Witness"},
  { "player": "MegarushSM", "game": "Super Metroid"},
  { "player": "MegarushSMW", "game": "Super Mario World"},
  { "player": "MegarushLADX", "game": "Links Awakening DX"},
  { "player": "Mols", "game": "Minecraft"},
  { "player": "RiskofCyrus", "game": "Risk of Rain 2"},
  { "player": "RitzBlues", "game": "Blasphemous"},
  { "player": "RitzGreens", "game": "Slay the Spire"},
  { "player": "RitzOranges", "game": "Wargroove"},
  { "player": "RitzReds", "game": "Subnautica"},
  { "player": "RitzViolets", "game": "Super Metroid"},
  { "player": "RitzYellows", "game": "Timespinner"},
  { "player": "Stario", "game": "Super Mario World"},
  { "player": "Starlink", "game": "A Link to the Past"},
  { "player": "Starxaver", "game": "Kingdom Hearts 2"},
  { "player": "ZembarFF", "game": "Final Fantasy"},
  { "player": "ZembarHK", "game": "Hollow Knight"},
  { "player": "ZembarLTTP", "game": "A Link to the Past"},
  { "player": "ZembarRL", "game": "Rogue Legacy"},
  { "player": "ZembarSM", "game": "Super Metroid"},
  { "player": "ZembarSoE", "game": "Secret of Evermore"},
  { "player": "ZembarTS", "game": "Timespinner"},
  { "player": "ZembarWoL", "game": "Starcraft 2 Wings of Liberty"},
  { "player": "Zembsian", "game": "Stardew Valley"}
]
